// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"`
	Title    string  `json:"title"`
	Metadata *string `json:"metadata,omitempty"`
}

type Query struct {
}
