package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/uz6r/api/graph/model"
)

// Contents is the resolver for the contents field.
func (r *queryResolver) Contents(ctx context.Context, typeArg *string) ([]*model.Content, error) {
	return []*model.Content{
		{
			ID:    "1e42d389-8e29-4984-a1ee-42e3b5e45702",
			Type:  "project",
			Title: "Project 1",
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
