package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"

	"github.com/uz6r/api/graph/model"
)

// Entries is the resolver for the entries field.
func (r *queryResolver) Entries(ctx context.Context, typeArg *string) ([]*model.Entry, error) {
	filePath := filepath.Join("data", "entries.json")
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	type tempEntry struct {
		ID          string          `json:"id"`
		Type        string          `json:"type"`
		Title       string          `json:"title"`
		Slug        *string         `json:"slug"`
		Description *string         `json:"description"`
		URL         *string         `json:"url"`
		ImageURLs   []string        `json:"image_urls"`
		Created     *string         `json:"created"`
		Updated     *string         `json:"updated"`
		Published   *string         `json:"published"`
		Archived    *bool           `json:"archived"`
		Metadata    json.RawMessage `json:"metadata"`
	}

	var tempEntries []tempEntry
	if err := json.Unmarshal(data, &tempEntries); err != nil {
		return nil, err
	}

	var entries []*model.Entry
	for _, te := range tempEntries {
		if typeArg != nil && *typeArg != "" && te.Type != *typeArg {
			continue
		}
		var metadataStr *string
		if len(te.Metadata) > 0 && string(te.Metadata) != "null" && string(te.Metadata) != "{}" {
			s := string(te.Metadata)
			metadataStr = &s
		}
		entries = append(entries, &model.Entry{
			ID:          te.ID,
			Type:        te.Type,
			Title:       te.Title,
			Slug:        te.Slug,
			Description: te.Description,
			URL:         te.URL,
			ImageUrls:   te.ImageURLs,
			Created:     te.Created,
			Updated:     te.Updated,
			Published:   te.Published,
			Archived:    te.Archived,
			Metadata:    metadataStr,
		})
	}
	return entries, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
